---
- name: Playbook to configure IPA server
  hosts: ipaserver
  become: true

  roles:
  - role: ipaserver
    state: present

  post_tasks:
  
  - name: Enable ACME IdM service
    ansible.builtin.shell: "ipa-acme-manage enable"

  - name: Set ACME to automatically remove expired certificates from the CA
    ansible.builtin.shell: | 
      ipa-acme-manage pruning --enable --cron "0 0 1 * *"

  - name: Check if the ACME service is installed and enabled
    ansible.builtin.shell: "ipa-acme-manage status"
