[ipaserver]
server.idm.example.com ansible_ssh_private_key_file="{{ local_sshkey_file }}" ansible_host=<CHANGE_ME> ansible_user="{{ azure_vm_admin_user }}"

[ipaserver:vars]
ipaserver_domain=<CHANGE_ME>
ipaserver_realm=<CHANGE_ME>

ipaserver_setup_dns=true
ipaserver_auto_forwarders=true
# Required for ACME
ipaserver_random_serial_numbers=true

# Minimum 8 char lenght
ipaadmin_password=<CHANGE_ME>
# Minimum 8 char lenght
ipadm_password=<CHANGE_ME>


[all:vars]
#Same as ipaserver_domain
idm_domain=<CHANGE_ME>

### ARO stuff
# RG where aor-vnet-XXX network lives. Not to confuse with the RG where ARO VMs live.
aro_network_resource_group=<CHANGE_ME>
aro_network=<CHANGE_ME>

### Azure stuff
azure_vm_resource_group=<CHANGE_ME>
azure_vm_name=<CHANGE_ME>
azure_vm_network=<CHANGE_ME>
azure_vm_subnet=<CHANGE_ME>

# Don't touch
azure_vm_size=Standard_D2s_v3
azure_vm_admin_user=azureuser
azure_vm_sg=idm-sec-group
azure_vm_public_ip=idm-public-ip
azure_vm_nic=idm-nic

# Azure Image info
azure_vm_image_offer=RHEL
azure_vm_image_publisher=RedHat
azure_vm_image_sku=95_gen2
azure_vm_image_version=9.5.2025040316

### Local stuff
# Generate local SSH keys for Azure VM
local_sshkey_folder="./sshkeys/"
local_sshkey_file="{{ local_sshkey_folder }}id_rsa"
local_sshkey_pub_file="{{ local_sshkey_folder }}id_rsa.pub"
