collections:
- name: community.general
  version: 10.6.0
- name: redhat.rhel_system_roles
  version: 1.88.9
- name: redhat.rhel_idm
  version: 1.13.2
- name: azure.azcollection
  version: 3.3.1
- name: redhat.openshift
  version: 4.0.1
- name: kubernetes.core
  version: 5.2.0
