apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: idm-dev
spec:
  acme:
    preferredChain: ""
    privateKeySecretRef:
      name: idm-dev-issuer-private-key
    server: https://idm.acme.example.com/acme/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: openshift-default